# Generated by Django 3.2.21 on 2023-09-13 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('creator', models.CharField(max_length=70, verbose_name='投稿者')),
                ('modifier', models.CharField(max_length=70, verbose_name='更新者')),
                ('created', models.DateTimeField(verbose_name='投稿日時')),
                ('modified', models.DateTimeField(verbose_name='更新日')),
                ('liked', models.IntegerField(default=0, verbose_name='いいね数')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=30, verbose_name='コメント作者')),
                ('body', models.TextField(verbose_name='コメント')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='コメント投稿日時')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='polls.article', verbose_name='記事')),
            ],
        ),
    ]
